### ISSUE TITLE
Add "Provider" parameter in External Tickets Schema

### ISSUE THREAD

**Issue by borivojetasovac** [matteeyah/respondo#145] opened 2019-12-01 20:26 UTC
If a user is sending manual POST requests from two different providers (for example HackerNews and YouTube), we won't be able to differentiate these tickets.

We should add provider as an allowed POST argument.

**Comment by matteeyah** [comment] 2019-12-01 20:38
Duplicate of https://github.com/matteeyah/respondo/issues/133

**Closed by matteeyah** 2019-12-01 20:38 UTC
