### ISSUE TITLE
Enable tags

### ISSUE THREAD

**Issue by borivojetasovac** [matteeyah/respondo#188] opened 2020-04-03 12:32 UTC
When a CA is starting a day, it should be able to have an overview of high priority tickets that somebody from the previous time zone assigned to them or marked as 'urgent'.

Either as an option to sort tickets by tags/priority or by having a 'Personal view' or 'Urgent' view.

**Comment by matteeyah** [comment] 2020-04-04 02:17
This is a duplicate of https://github.com/matteeyah/respondo/issues/4 and https://github.com/matteeyah/respondo/issues/99.

**Closed by matteeyah** 2020-04-04 02:17 UTC
